[build]
publish = "."
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"

[[headers]]
for = "/files/mock_test_answer/*.kt"
  [headers.values]
  Content-Type = "text/plain; charset=utf-8"
  X-Content-Type-Options = "nosniff"

[[headers]]
for = "/files/mock_test_answer/*.xml"
  [headers.values]
  Content-Type = "text/plain; charset=utf-8"
  X-Content-Type-Options = "nosniff"

[[headers]]
for = "/files/**/*.md"
  [headers.values]
  Content-Type = "text/plain; charset=utf-8"
  X-Content-Type-Options = "nosniff"

[[headers]]
for = "/files/*.md"
  [headers.values]
  Content-Type = "text/plain; charset=utf-8"
  X-Content-Type-Options = "nosniff"
